-- AlterTable
ALTER TABLE "Aluno" ALTER COLUMN "rg_numero" DROP NOT NULL,
ALTER COLUMN "rg_orgao_emissor" DROP NOT NULL,
ALTER COLUMN "rg_uf_emissao" DROP NOT NULL,
ALTER COLUMN "cpf" DROP NOT NULL,
ALTER COLUMN "endereco_rua" DROP NOT NULL,
ALTER COLUMN "endereco_numero" DROP NOT NULL,
ALTER COLUMN "endereco_bairro" DROP NOT NULL,
ALTER COLUMN "endereco_cidade" DROP NOT NULL,
ALTER COLUMN "endereco_estado" DROP NOT NULL,
ALTER COLUMN "endereco_cep" DROP NOT NULL,
ALTER COLUMN "pais_origem" DROP NOT NULL,
ALTER COLUMN "estado_origem" DROP NOT NULL,
ALTER COLUMN "cidade_origem" DROP NOT NULL,
ALTER COLUMN "genero" DROP NOT NULL,
ALTER COLUMN "estado_civil" DROP NOT NULL,
ALTER COLUMN "possui_deficiencia" DROP NOT NULL,
ALTER COLUMN "data_nascimento" DROP NOT NULL,
ALTER COLUMN "pais_residencia" DROP NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT now(),
ALTER COLUMN "updated_at" SET DEFAULT now();
